language: c

cache: ccache

os:
  - linux

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev
  - sudo apt install rpm

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && make package

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: d2jyQuMRCE/HGrzX66bOsd4PYaYCuaeDzwW+1DR15RRpHOnwa/9a1bM3w7adgPO+KIUc44QvtOhLrcfdPmc59BHymy+N5/W/Dymz+PN6YLRJ4ICbZT1xQGJ3SN1Hp1uqB3FFfF4Tcaz0i/awmvs2BmOvS+KWTh7sUWayNRtb4jDbiqpiSmNRjo7iJbQwdk7zjK7jBSVRqTjA4SxMfU5LlEy6829hxzX49wKLQga++iCOM9fV+AJ09Ut58JOtDy2PsOshpkgpr2JD2Qdvj3TFYxYtCFR4bJcEX5vjRt5Z/3/uYbA4DPvt0qFjdLQhhpwRFyOx13W2VgQb9PEYSf02/kGp0is6q9Jp3H9FmRvYv6TXhKhHv8ujyJp1QRDttVovmk2DSWm54Xh3et5CoGM3pQQug3QVoECWRi9gDc460Ibp2WPL0b9f6sYhHp7U8MTmXjFX38VM1RVVyaIqOVV/KwHqCfM3BhgcVQ05KuwP9Ydpk8Rt93ta6go4diy+Ij2Nd+e84rpGT+4hQalqMTZ7rxtQ1NqvQGcMHzoSVfPlEIvIHNB6hn0WnsQSC77360KbvBT8ZJz2lp0Ql3rt4DOyJQlRUbRig2P8s6YMQUVuoCpnR8LBpyiIUjioLonE0gHtKwj1A4oGwFKwYjC6hBSKs1ig8BzjIjXsyFmaRYR+Kj0=
  file:
    - audiality2-*-Linux.deb
    - audiality2-*-Linux.rpm
    - audiality2-*-Linux.tar.bz2
  on:
    tags: true
    repo: olofson/audiality2
